services:
  - name: my_project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080
    env:
      - name: DJANGO_SETTINGS_MODULE
        value: my_project.settings
      - name: DJANGO_SECRET_KEY
        value: zeabur
      - name: DJANGO_DEBUG
        value: "False"
      - name: DATABASE_URL
        value: postgres://postgres:postgres@postgres:5432/postgres
      - name: REDIS_URL
        value: redis://redis:6379/1
    depends_on:
      - postgres
      - redis
    command: python migrate.py && gunicorn my_project.wsgi:application --bind 0.0.0.0:8080

  - name: postgres
    image: postgres:15
    env:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres
      - name: POSTGRES_DB
        value: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  - name: redis
    image: redis:7
    command: redis-server --requirepass zeabur
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 