# Generated by Django 4.2.7 on 2025-04-01 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='檔案')),
                ('category', models.CharField(choices=[('news', '新聞'), ('report', '報告'), ('analysis', '分析'), ('other', '其他')], default='other', max_length=20, verbose_name='類別')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最後修改時間')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下載次數')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'ordering': ['-upload_time'],
            },
        ),
    ]
