# Generated by Django 4.2.20 on 2025-04-07 05:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('file', models.FileField(blank=True, null=True, upload_to=documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt'])], verbose_name='文件')),
                ('external_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='外部連結')),
                ('source', models.CharField(choices=[('manual', '手動上傳'), ('google_drive', 'Google Drive'), ('n8n', 'n8n生成')], default='manual', max_length=20, verbose_name='來源')),
                ('upload_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='上傳時間')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最後修改')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下載次數')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否啟用')),
                ('category', models.CharField(choices=[('market_quotes', '市場行情'), ('daily_reports', '每日報告'), ('macro_reports', '宏觀報告'), ('stock_reports', '股票報告')], db_index=True, max_length=20, verbose_name='類別')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
            ],
            options={
                'verbose_name': '投資文件',
                'verbose_name_plural': '投資文件',
                'ordering': ['-upload_time'],
                'indexes': [models.Index(fields=['category'], name='documents_i_categor_6c4589_idx')],
            },
        ),
        migrations.CreateModel(
            name='InsuranceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('file', models.FileField(blank=True, null=True, upload_to=documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt'])], verbose_name='文件')),
                ('external_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='外部連結')),
                ('source', models.CharField(choices=[('manual', '手動上傳'), ('google_drive', 'Google Drive'), ('n8n', 'n8n生成')], default='manual', max_length=20, verbose_name='來源')),
                ('upload_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='上傳時間')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最後修改')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下載次數')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否啟用')),
                ('category', models.CharField(choices=[('products', '產品資料'), ('proposals', '計畫書'), ('promotions', '產品優惠'), ('info', '保險資訊')], db_index=True, max_length=20, verbose_name='類別')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
            ],
            options={
                'verbose_name': '保險文件',
                'verbose_name_plural': '保險文件',
                'ordering': ['-upload_time'],
                'indexes': [models.Index(fields=['category'], name='documents_i_categor_c156ae_idx')],
            },
        ),
    ]
