# Generated by Django 4.2.20 on 2025-04-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentdocument',
            name='category',
            field=models.CharField(choices=[('quotes', '行情報價'), ('daily', '每日報告'), ('macro', '總經報告'), ('stocks', '個股報告')], db_index=True, max_length=20, verbose_name='類別'),
        ),
    ]
