# Generated by Django 4.2.20 on 2025-04-09 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='標籤名稱')),
                ('slug', models.SlugField(unique=True, verbose_name='URL標識')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '標籤',
                'verbose_name_plural': '標籤',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='auto_category',
            field=models.CharField(blank=True, max_length=50, verbose_name='自動分類'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='preview_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='預覽連結'),
        ),
        migrations.AddField(
            model_name='investmentdocument',
            name='auto_category',
            field=models.CharField(blank=True, max_length=50, verbose_name='自動分類'),
        ),
        migrations.AddField(
            model_name='investmentdocument',
            name='preview_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='預覽連結'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='tags',
            field=models.ManyToManyField(blank=True, to='documents.tag', verbose_name='標籤'),
        ),
        migrations.AddField(
            model_name='investmentdocument',
            name='tags',
            field=models.ManyToManyField(blank=True, to='documents.tag', verbose_name='標籤'),
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', '查看'), ('create', '創建'), ('update', '更新'), ('delete', '刪除'), ('download', '下載'), ('search', '搜索')], max_length=20, verbose_name='操作類型')),
                ('document_type', models.CharField(choices=[('insurance', '保險文件'), ('investment', '投資文件')], max_length=20, verbose_name='文件類型')),
                ('document_id', models.IntegerField(blank=True, null=True, verbose_name='文件ID')),
                ('document_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='文件標題')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用戶代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作時間')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='詳細信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '用戶行為日誌',
                'verbose_name_plural': '用戶行為日誌',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='documents_u_user_id_c8d0cb_idx'), models.Index(fields=['action', 'created_at'], name='documents_u_action_c7dba6_idx'), models.Index(fields=['document_type', 'created_at'], name='documents_u_documen_b5ffd7_idx')],
            },
        ),
    ]
