# Generated by Django 4.2.20 on 2025-04-01 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='發布時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後修改時間')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時間')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('is_important', models.BooleanField(default=False, verbose_name='是否重要')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='發布者')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-is_important', '-created_at'],
            },
        ),
    ]
